name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Запускать только при пуше в ветку main, измените на нужную ветку, если требуется

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t username/repository:latest .

      - name: Push Docker image to Docker Hub
        run: docker push username/repository:latest
